[project]
name = "ai-financial-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-ollama>=1.0.1",
    "pandas>=2.3.3",
    "streamlit>=1.52.2",
    "yfinance>=1.0",
]
